# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
