# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=1000),
        ),
    ]
