# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160807_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
