# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160807_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
